{
  lib,
  fetchurl,
  linkFarmFromDrvs,
}:

# Takes a path to a mods.lock.json file (generated by update-modrinth-mods)
# and returns a derivation containing all the mod JARs as a symlink farm.
#
# Usage:
#   symlinks.mods = fetchModrinthMods ./mods.lock.json;
#
# To combine with additional mods not from Modrinth:
#   symlinks.mods = pkgs.linkFarmFromDrvs "mods" (
#     (pkgs.fetchModrinthMods ./mods.lock.json).drvs
#     ++ [ (pkgs.fetchurl { url = "..."; hash = "..."; }) ]
#   );
#
# The lock file is a JSON object keyed by mod slug:
# {
#   "fabric-api": {
#     "version": "0.115.0+1.21.1",
#     "versionId": "9YVrKY0Z",
#     "url": "https://cdn.modrinth.com/data/...",
#     "hash": "sha512-...",
#     "filename": "fabric-api-0.115.0+1.21.1.jar"
#   },
#   ...
# }
lockFile:
let
  lock = lib.importJSON lockFile;

  mods = lib.mapAttrsToList (
    slug: entry:
    fetchurl {
      inherit (entry) url hash;
      name = entry.filename;
    }
  ) lock;
in
# Expose the individual mod derivations as `.drvs` so users can extend the
# mod list with additional non-Modrinth mods (see usage comment above).
(linkFarmFromDrvs "mods" mods) // { drvs = mods; }
